### ISSUE TITLE
rosparam error

### ISSUE THREAD

**Issue by marceloparavisi** [KCL-Planning/rosplan_demos#21]
Hello 

I'm trying to run the turtlebo2 demo,but I'm receiving an error. 

I'm running the following commands:
Terminal 1: 
`roslaunch rosplan_turtlebot2_demo turtlebot.launch`
Terminal 2:
`rosrun rosplan_turtlebot2_demo turtlebot_explore.bash`

In terminal 1, received the following message:

> Waypoint not found in parameter server. /rosplan_demo_waypoints/wp1

I think the rosplan_interface_movebase(RPMoveBase.cpp) is going up before the rosplan_roadmap_server(RPRoadmapServer.cpp).

So solve this error, i added on line 39 (https://github.com/KCL-Planning/rosplan_demos/blob/master/rosplan_turtlebot2_demo/launch/turtlebot.launch)
`<param name="wp_namespace" value="/rosplan_demo_waypoints/wp" />`

so, the code looks like:

`<node pkg="rosplan_interface_movebase" type="rpmovebase" name="rosplan_interface_movebase" respawn="false" output="screen">`
`        <param name="knowledge_base" value="rosplan_knowledge_base" />`
`        <param name="action_server" value="/move_base" />`
`        <param name="pddl_action_name" value="goto_waypoint" />`
`        <param name="action_dispatch_topic" value="/rosplan_plan_dispatcher/action_dispatch" />`
`        <param name="action_feedback_topic" value="/rosplan_plan_dispatcher/action_feedback" />`
`        <param name="wp_namespace" value="/rosplan_demo_waypoints/wp" />`
`    </node>`

Regards,
Marcelo

**Comment by oscar-lima** [comment]
Issue was caused by line 747 of https://github.com/KCL-Planning/rosplan_demos/commit/9d9f36bb77ccb7848f45676f5a21af9dfd1ee1d0#

Thanks for the bug report, I have created PR #35 to fix this
