### ISSUE TITLE
ROB-IS repo is gone?

### ISSUE THREAD

**Issue by corot** [KCL-Planning/rosplan_demos#24]
The ROB-IS repo pointed by https://github.com/sarah-keren/ROB-IS doesn't exist.
I suppose there must be hidden_costs_generator package.

**Comment by m312z** [comment]
Hello Jorge,

That repo is currently private. I'll see if there are any obstacles to making it public as soon as possible. Until then, the Waypoint Sampling demo can't be run!

Michael

**Comment by corot** [comment]
That would be great!
And thanks for your fast response

**Comment by oscar-lima** [comment]
https://github.com/sarah-keren/ROB-IS repo is online, closing issue
