### ISSUE TITLE
error in executing Turtlebot3 Exploration

### ISSUE THREAD

**Issue by bilal9876** [KCL-Planning/rosplan_demos#29]
every tting is download and build very well.

but when i try to launch the  the demo with the turtlebot 3 in ROS melodic
export TURTLEBOT3_MODEL=waffle
roslaunch rosplan_turtlebot3_demo turtlebot.launch

[ WARN] [1582910440.670049163]: Request for map failed; trying again..
''''
'''''
[ERROR] [1582910442.440204388]: Client [/rviz] wants topic /rosplan_roadmap_server/viz/waypoints to have datatype/md5sum [visualization_msgs/MarkerArray/d155b9ce5188fbaf89745847fd5882d7], but our version has [visualization_msgs/Marker/4048c9de2a16f4ae8e0538085ebf1b97]. Dropping connection.
''''
'''
[Err] [REST.cc:205] Error in REST request
''''
''''
[ WARN] [1582910443.589077896, 1.030000000]: global_costmap: Parameter "plugins" not provided, loading pre-Hydro parameters
[ WARN] [1582910443.956252840, 1.390000000]: local_costmap: Parameter "plugins" not provided, loading pre-Hydro parameters

###  ****I tried to continue the demo as in:****

https://github.com/KCL-Planning/rosplan_demos/commit/3813d9c66d19a252617c4fd9da1606ceed577f4e?diff=split

 In a second terminal I run the following  

rosrun rosplan_turtlebot3_demo turtlebot_explore.bash

but there is an error in 

Calling planner interface.
ERROR: service [/rosplan_planner_interface/planning_server] responded with an error:

**Comment by gerardcanal** [comment]
Hi bilal9876,
It should be fixed by #30. You may also face #20, in such case fix the bash scripts as in https://github.com/KCL-Planning/rosplan_demos/pull/25/files?file-filters%5B%5D=.bash#diff-31a2c204c826fbea9a146d8c36a08aa5 

If it still doesn't work please reopen this issue.

**Comment by gerardcanal** [comment]
hello Mr. gerardcanal . it doesnot work , i have changed the three files but also it didnot work. the same error. 
iam using turtlebot3 demos not the turtlebo2 demo . so, should i change the files in turtlebpt3_demo.

_Originally posted by @bilal9876 in https://github.com/KCL-Planning/rosplan_demos/pull/25#issuecomment-592661881_

Hi @bilal9876,
Better to have the conversation here as the other is a different issue.
Did you update the repository? To do so you need to run:

```
roscd rosplan_demos
git pull
```
And this should update the changes.

**Comment by bilal9876** [comment]
bilal@bilal-HP-ZBook-15-G3:~/rosplan_catkin_ws/src/rosplan_demos/rosplan_demos$ git pull
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 10 (delta 5), reused 8 (delta 5), pack-reused 0
Unpacking objects: 100% (10/10), done.
From https://github.com/KCL-Planning/rosplan_demos
   c206e43..e4340c7  master     -> origin/master
Updating c206e43..e4340c7
error: Your local changes to the following files would be overwritten by merge:
	rosplan_turtlebot2_demo/config/turtlebot2.rviz
Please commit your changes or stash them before you merge.
Aborting


as you see i cannot do git pull. should i remove the rosplan_demos/rosplan_demos/ and git pull again

**Comment by gerardcanal** [comment]
Hello,
This happens with git when you have changes that were not saved. You have two options to fix it:
1. Remove the repository and reload it again
2. To keep the changes you did, you can run:
```
git stash
git pull
git stash pop
```

**Comment by bilal9876** [comment]
ok. done .
export TURTLEBOT3_MODEL=waffle
roslaunch rosplan_turtlebot3_demo turtlebot.launch

there is no errors just one 
[Err] [REST.cc:205] Error in REST request

and two warn message 
[ WARN] [1582917358.685580585, 1.570000000]: local_costmap: Parameter "plugins" not provided, loading pre-Hydro parameters
[ WARN] [1582917358.320507478, 1.210000000]: global_costmap: Parameter "plugins" not provided, loading pre-Hydro parameters

but it seems work for the launch commands

if i execute the bash 
rosrun rosplan_turtlebot3_demo turtlebot_explore.bash

Calling planner interface.
ERROR: service [/rosplan_planner_interface/planning_server] responded with an error:

do may be the wrapper for AI planner is missed or some thing .

i appologize , forgive me plz .

thank you

**Comment by bilal9876** [comment]
i want to mention that rosplan_tutorial3_demo is not changed but only the rosplan_tutorial2_demo.

should i change also the turtlebot_explore.bash and turtlebot_explore_wp_from_file.bash (remove kcl_rosplan) and should i change the turtlebot3.rviz in config folder that is existed in rosplan_tutorial3_demo.

**Comment by gerardcanal** [comment]
Hi,
No worries. I am not sure about what can be the error now. Can you me sure you have the last version of rosplan and that you ran the catkin build command?

If it still errors after that please send the whole screenshot of the error screen
 Do not worry about the rest error and the warnings for now.

I will be unavailable until next Monday.

**Comment by gerardcanal** [comment]
Yes, If you are using Ubuntu 18 or ros melodic you need to change it also in tuetlebot3 demo.

**Comment by bilal9876** [comment]
ok . i will try to modify the turtlebot3_ demo folder also. i use catkin_make not catkin_build any way have a nice weekend. i will updated later on

**Comment by bilal9876** [comment]
just one error .
[ERROR] [1582918607.343676145, 53.370000000]: Waypoint not found in parameter server

**Comment by gerardcanal** [comment]
Closing this as it's the same as it is now the same issue as #21.

**Comment by bilal9876** [comment]
hello Gerard.
i think we must change the bash file "/scripts/turtlebot_explore.bash" of turtlebot3_demos to execute or call the turtlebot_explore_common.bash that is found in rosplan_turtlebot3_demo folder. so 

bash `rospack find rosplan_turtlebot2_demo`/scripts/turtlebot_explore_common.bash.

must be changed into 

bash `rospack find rosplan_turtlebot3_demo`/scripts/turtlebot_explore_common.bash.

but both command is working but for latter use.

also the same must be done for the turtlebot_explore_wp_from_file.bash file.
