### ISSUE TITLE
Unable to load type [rosplan_interface_mapping/CreatePRM]

### ISSUE THREAD

**Issue by rakhmanu** [KCL-Planning/rosplan_demos#34]
Hi,

I am following this tutorial:  rosplan_turtlebot2_demo and when i run turtlebot_explore.bash script, i have got the following errors which are attached below 

![rosplan](https://user-images.githubusercontent.com/41294651/78327573-2dbcc680-75b8-11ea-826e-e7635a909556.png)

Help me please to solve it 
Thank you

**Comment by gerardcanal** [comment]
Hello,
Seeing the messages it seems like the workspace has bot been built correctly or the nodes have not been launched.

Can you make sure that you have run `catkin_make` or `catkin build`? If so, have you executed `roslaunch rosplan_turtlebot2_demo turtlebot.launch` in a different terminal?

Best,
Gerard

**Comment by m312z** [comment]
Hello,

Also, make sure that you have run "source devel/setup.bash" in each terminal you are using (or placed it in your .bashrc).

Michael

**Comment by oscar-lima** [comment]
Sorry I just noticed that the instruction to clone ROSPlan itself is missing in the tutorial, this is:

git clone https://github.com/KCL-Planning/ROSPlan.git

Have you done that? maybe it could be the issue.

By the way I will update the tutorial to include this instruction

**Comment by rakhmanu** [comment]
> Sorry I just noticed that the instruction to clone ROSPlan itself is missing in the tutorial, this is:
> 
> git clone https://github.com/KCL-Planning/ROSPlan.git
> 
> Have you done that? maybe it could be the issue.
> 
> By the way I will update the tutorial to include this instruction

Dear, 

I have done ROSPlan clone correctly, but the result is still the same...

**Comment by rakhmanu** [comment]
> Hello,
> Seeing the messages it seems like the workspace has bot been built correctly or the nodes have not been launched.
> 
> Can you make sure that you have run `catkin_make` or `catkin build`? If so, have you executed `roslaunch rosplan_turtlebot2_demo turtlebot.launch` in a different terminal?
> 
> Best,
> Gerard

Dear,

Yes, i think also the problem is in workspace. When i try to run catkin_make, it causes some problems as following

![pop](https://user-images.githubusercontent.com/41294651/78420638-db4cda00-768b-11ea-9fba-807ce681f90e.png)
 
But cannot fix it..

**Comment by rakhmanu** [comment]
> Hello,
> 
> Also, make sure that you have run "source devel/setup.bash" in each terminal you are using (or placed it in your .bashrc).
> 
> Michael

Dear,

Yes,  i  run "source devel/setup.bash" in each terminal  But still the problem occurs...

**Comment by rakhmanu** [comment]
> > Sorry I just noticed that the instruction to clone ROSPlan itself is missing in the tutorial, this is:
> > git clone https://github.com/KCL-Planning/ROSPlan.git
> > Have you done that? maybe it could be the issue.
> > By the way I will update the tutorial to include this instruction
> 
> Dear,
> 
> I have done ROSPlan clone correctly, but the result is still the same...

I am so sorry, i missed one step in ROSPlan tutorial instruction
So, its solved 
Thank you all
