### ISSUE TITLE
Waypoint not found in parameter server

### ISSUE THREAD

**Issue by rakhmanu** [KCL-Planning/rosplan_demos#36]
Hi,

I tried to run rosplan_turtlebot2_demo, so I can see the generated waypoints, however the robot does not move according to those waypoints( does not move at all ) And the error says waypoint not found in parameter server

Help plz

Thank you

**Comment by oscar-lima** [comment]
Hi, yes. The problem was noticed in issue #21 and fixed in #35. However was not merged yet (it is now). Please pull #35 (build ws again -> catkin build) and try again. Please let us now if works ;)

**Comment by oscar-lima** [comment]
will close for now, feel free to reopen if problem remains
