### ISSUE TITLE
Create python action interface demo

### ISSUE THREAD

**Issue by oscar-lima** [KCL-Planning/rosplan_demos#37]
From ROSPlan mailing list:

```
Hi, I have a question. Is it possible to define an action interface in Python?
If yes, is it possible to have a simple example?
```

**Comment by gerardcanal** [comment]
That is a good idea. Though maybe I see it more as an issue for the main rosplan, we could create there an abstract python class as it's done now in C++?

**Comment by oscar-lima** [comment]
good point, absolutely!

**Comment by m312z** [comment]
An example would definitely be useful as well - perhaps a move_base interface that mirrors the example c++ one?

**Comment by oscar-lima** [comment]
implemented, waiting for PR feedback.

**Comment by oscar-lima** [comment]
closed due to https://github.com/KCL-Planning/rosplan_demos/pull/39 , in summary the action interface was favored instead as it is more complete (see action interface PR here: KCL-Planning/ROSPlan#285)
