### ISSUE TITLE
something wrong in rosplan_turtlebot3_demos

### ISSUE THREAD

**Issue by ytbai19** [KCL-Planning/rosplan_demos#44]
when I run the demo,I want to reset my waypoint.yaml.But it didn't work.
Then I found there is an error in this file "turtlebot_explore_wp_from_file.bash".
It should be "turtlebot3" rather than "turtlebot2".

**Comment by gerardcanal** [comment]
Thanks for reporting it, @ytbai19!

I just made a Pull Request to fix the issue.
