### ISSUE TITLE
RLException: unused args [assignment_value] for include of....

### ISSUE THREAD

**Issue by zz86** [KCL-Planning/rosplan_demos#55]
Hi. 
I am new to rosplan. when I launch the file `rosplan_demos/launch/simulated_actions.launch`, there is something wrog...like below
```
frankamini@frankamini:~$ roslaunch rosplan_demos simulated_actions.launch 
... logging to /home/frankamini/.ros/log/b844d212-ebd4-11ed-837d-5ce42a0b1427/roslaunch-frankamini-24226.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: unused args [assignment_value] for include of [/home/frankamini/zzm/ROS_Plan/src/rosplan/rosplan_planning_system/launch/includes/simulated_action.launch]
The traceback for the exception was written to the log file

```
When I checked this file I found `<arg name="assignment_value" value="100" />`. then I checked `rosplan_planning_system/launch/includes/simulated_action.launch`. I found that there is no such parameter in this file. Is there something wrong here？What does this parameter do? 

then I commented this code  `<arg name="assignment_value" value="100" />`. I successfully launched this file. 

Thank you very much for your reply!

**Comment by gerardcanal** [comment]
Hi @zz86,
the rosplan_demos package has some legacy code and is not a full demo, all the completed demos are in their own package so they should work. We'll check about the launches in the rosplan_demos metapackage and clear it as needed. Thanks for letting us know!
