### ISSUE TITLE
when i run 'roslaunch rosplan_turtlebot2_demo turtlebot.launch', it errors

### ISSUE THREAD

**Issue by xhy3054** [KCL-Planning/rosplan_demos#9]
the error is:

roslaunch rosplan_turtlebot2_demo turtlebot.launch
... logging to /home/xhy/.ros/log/90324a18-86cd-11e9-b4c1-30f9eda9897e/roslaunch-xhy-SVF14316SCB-29067.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
xacro.py is deprecated; please use xacro instead
unused args [problem_path, autom_gen_problem_path, data_path, domain_path] for include of [/home/xhy/ROSPlan/src/rosplan/rosplan_planning_system/launch/interfaced_planning_system.launch]
The traceback for the exception was written to the log file

could you tell me how can i fix it? thanks

**Comment by oscar-lima** [comment]
Hello,

If I am not mistaken this should be a warning and not an error. It comes from the turtlebot launch file located [here](https://github.com/turtlebot/turtlebot_simulator/blob/indigo/turtlebot_gazebo/launch/includes/kobuki.launch.xml), however I see that this warning was addressed already in [this commit](https://github.com/turtlebot/turtlebot_simulator/commit/cda63a5be08b5af6baae0e38071b8fd414bad811) but probably is not yet in the debian version.

So your options are:

- wait until the change is released (ignore the warning as it has no effect on the demo execution, is just an annoying warning)
- clone from source the [https://github.com/turtlebot/turtlebot_simulator/tree/indigo/turtlebot_gazebo](turtlebot_simulator) pkg
- create temp custom turtlebot launch files, living under a custom ROS pkg and change line 7 of [rosplan turtlebot.launch](https://github.com/KCL-Planning/rosplan_demos/blob/master/rosplan_turtlebot2_demo/launch/turtlebot.launch) to point to your custom launch file
